[WIP] #18 add route api/user/bids
PlebFM/PlebFM pull request #39
Opened 2022-12-31 22:11 UTC by bnonni

WIP PR - actively developing

2023-01-04 23:18 UTC, bnonni commented
No longer WIP. Please review at leisure @alexlwn123

2023-01-05 06:05 UTC, alexlwn123 commented on pages/api/bid/history.ts
> +export default connectDB(handler);
Did the prettier/husky script not run automatically? Looks like the formatting didn't get fixed 😢

2023-01-05 06:09 UTC, alexlwn123 requested changes
Now that `main` is stable (builds successfully), I added the branch protections back in. Just pull in main and double check that `npm build` succeeds.

Other than that LGTM! Thanks!

2023-01-05 11:56 UTC, bnonni commented on pages/api/bid/history.ts
> +export default connectDB(handler);
It didn't, but after checking out main, running npm install and then running npm run format, im all good. latest push should be good to go.

2023-01-05 11:58 UTC, bnonni reviewed
Formatting fixed (i think)

2023-01-05 11:59 UTC, bnonni commented
`npm run build` is throwing errors 

```
./components/AlbumScreen.tsx:9:3
Type error: Member 'track' implicitly has an 'any' type.

   7 | import NavBar from './NavBar';
   8 | export default function AlbumScreen(props: {
>  9 |   track;
     |   ^
  10 |   setSongConfirmed;
  11 |   cancelSong;
  12 | }) {

./components/PaymentScreen.tsx:10:3
Type error: Member 'song' implicitly has an 'any' type.

   8 | 
   9 | function PaymentScreen(props: {
> 10 |   song;
     |   ^
  11 |   readyToCheckout;
  12 |   invoicePaid;
  13 |   setInvoicePaid;
```

2023-01-05 16:02 UTC, alexlwn123 approved these changes
Looks great. Thanks!

2023-01-05 16:03 UTC, merged